version: '3'
services:
  mysqlDB:
    image: mysql:5.7
    container_name: mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - ./mySqlDB:/docker-entrypoint-initdb.d
    networks:
      app-network:
        ipv4_address: 172.16.238.10

  webserver:
    image: apache:latest
    container_name: webserver
    volumes:
      - ./admin_area:/var/www/html/admin_area
      - ./books:/var/www/html/books
      - ./movies:/var/www/html/movies
      - ./mySqlDB:/var/www/html/mySqlDB
      - ./siteImages:/var/www/html/siteImages
      - ./index.php:/var/www/html/index.php
    ports:
      - "80:80"
    networks:
      app-network:
        ipv4_address: 172.16.238.11

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
