version: '3'
services:
  mysqlDB:
    image: mysql:5.7
    container_name: mysqlDB
    volumes:
      - ./mySqlDB:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - app-network
    hostname: mysqlDB

  webserver:
    image: apache:latest
    container_name: webserver
    volumes:
      - ./admin_area:/var/www/html/admin_area
      - ./books:/var/www/html/books
      - ./movies:/var/www/html/movies
      - ./siteImages:/var/www/html/siteImages
      - ./index.php:/var/www/html/index.php
    environment:
      MYSQL_HOST: 134.209.175.249
    ports:
      - "80:80"
    networks:
      - app-network
    hostname: webserver

networks:
  app-network:
    driver: bridge
